# Validating the Clusters
In this experiment, multiple metrics will be employed in order to validate the clusters. Metrics such as adjusted rand index, mutual information based scores, homogeneity, completeness and V-measure can not be used in this work because they require the ground truth (true labels) of the data.

Number of clusters used: 82.

## Loading the Data

In [1]:
import sys
import os
sys.path.append('../')
from src import reader as r
from src import visualization as v

/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
%matplotlib notebook
import numpy as np
import pandas as pd
import sklearn
print(sklearn.__version__)
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.metrics import davies_bouldin_score, calinski_harabaz_score

0.20.0


In [3]:
X = r.readBOW()
npX = X
print(npX)
print(X[:10])
print(X.shape)

['word2vec.csv', 'bags.csv', 'health.txt', 'health-dataset.zip', 'health-dataset']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(13229, 1203)


In [4]:
from MulticoreTSNE import MulticoreTSNE as TSNE

smp_sz = X.size
tsne_bow = TSNE(n_components=2, perplexity=10, verbose=True, n_jobs=-1)#500
tsne_bow_result = tsne_bow.fit_transform(X)

## Computing clusters

In [5]:
best_K = 82
print("#############################")
print("Best K =", best_K)
print("Applying K-means")
best_cluster = KMeans(n_clusters=best_K, n_jobs=-1)
best_cluster_result = best_cluster.fit(X)
y_pred = best_cluster_result.labels_
print("Finished")
print("#############################")   

#############################
Best K = 32
Applying K-means
Finished
#############################


### Checking if there are any cluster with 0 points

In [6]:
for i in range(best_K):
    print("Cluster "+str(i)+" has "+str(npX[y_pred==i].shape[0])+" elements")

Cluster 0 has 4927 elements
Cluster 1 has 295 elements
Cluster 2 has 175 elements
Cluster 3 has 128 elements
Cluster 4 has 386 elements
Cluster 5 has 194 elements
Cluster 6 has 272 elements
Cluster 7 has 225 elements
Cluster 8 has 402 elements
Cluster 9 has 130 elements
Cluster 10 has 234 elements
Cluster 11 has 98 elements
Cluster 12 has 183 elements
Cluster 13 has 524 elements
Cluster 14 has 312 elements
Cluster 15 has 362 elements
Cluster 16 has 78 elements
Cluster 17 has 331 elements
Cluster 18 has 323 elements
Cluster 19 has 78 elements
Cluster 20 has 146 elements
Cluster 21 has 182 elements
Cluster 22 has 143 elements
Cluster 23 has 199 elements
Cluster 24 has 458 elements
Cluster 25 has 135 elements
Cluster 26 has 303 elements
Cluster 27 has 166 elements
Cluster 28 has 465 elements
Cluster 29 has 296 elements
Cluster 30 has 114 elements
Cluster 31 has 965 elements


## Applying Metrics

### Davies Bouldin
This metric was not seen during classes but if the ground truth is not known, it can be used to evaluate the model. This index is defined as the average similarity between each cluster and its most similar one. Zero is the lowest possible score. Values closer to zero indicate a better partition.

In [7]:
score_db = davies_bouldin_score(npX,y_pred)
print("Davies Bouldin")
print(score_db)

Davies Bouldin
4.688744859279701


/opt/conda/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


### Kullback - Leibler

### Calinski and Harabaz
If the ground truth labels are not known, the Calinski-Harabaz index - also known as the Variance Ratio Criterion - can be used to evaluate the model, where a higher Calinski-Harabaz score relates to a model with better defined clusters.
To assess this metric, it must be computed for multiple clusters and visualy analyse the results.

In [8]:
score_ch = calinski_harabaz_score(npX,y_pred)
print("Calinski and Harabaz")
print(score_ch)

Calinski and Harabaz
45.17276135681402
