# Principal Component Analysis
In this notebook the Principal Component Analysis is used for dimensionality reduction of the data.

In [1]:
import sys
import os
sys.path.append('../')
from src import reader as r
from src import visualization as v
from src import metrics as m

/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
import numpy as np
import pandas as pd
import sklearn
print(sklearn.__version__)
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

0.20.0


In [3]:
X = r.readBOW()
print(X[:10])
print(X.shape)

['word2vec.csv', 'bags.csv', 'health.txt', 'health-dataset.zip', 'health-dataset']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(13229, 1203)


## Testing for Different Variances
### Keeping variance as 95%

In [4]:
pca = PCA(n_components = 0.95, svd_solver='full')
pca_result = pca.fit_transform(X)

The number of dimensions went from 1203 to 989

In [5]:
print(pca_result.shape)

(13229, 989)


In [6]:
best_K = 82
print("#############################")
print("Best K =", best_K)
print("Applying K-means")
best_cluster = KMeans(n_clusters=best_K, n_jobs=-1)
best_cluster_result = best_cluster.fit(pca_result)
y_pred = best_cluster_result.labels_
print("Finished")
print("#############################") 

#############################
Best K = 82
Applying K-means
Finished
#############################


In [7]:
m.applyAllMetrics(pca_result,y_pred)

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


Davies Bouldin
3.549276377469551

Calinski and Harabaz
32.29502591186293

Silhouette Score
0.05191594314540376



### Keeping variance of 90%

In [8]:
pca = PCA(n_components = 0.90, svd_solver='full')
pca_result = pca.fit_transform(X)

In [9]:
print(pca_result.shape)

(13229, 848)


In [10]:
print("#############################")
print("Best K =", best_K)
print("Applying K-means")
best_cluster = KMeans(n_clusters=best_K, n_jobs=-1)
best_cluster_result = best_cluster.fit(pca_result)
y_pred = best_cluster_result.labels_
print("Finished")
print("#############################") 

#############################
Best K = 82
Applying K-means
Finished
#############################


In [11]:
m.applyAllMetrics(pca_result,y_pred)

Davies Bouldin
3.423214085688029



/opt/conda/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


Calinski and Harabaz
34.249904622706524

Silhouette Score
0.0537600433958234



### Keeping variance of 85%

In [12]:
pca = PCA(n_components = 0.85, svd_solver='full')
pca_result = pca.fit_transform(X)

In [13]:
print(pca_result.shape)

(13229, 733)


In [14]:
print("#############################")
print("Best K =", best_K)
print("Applying K-means")
best_cluster = KMeans(n_clusters=best_K, n_jobs=-1)
best_cluster_result = best_cluster.fit(pca_result)
y_pred = best_cluster_result.labels_
print("Finished")
print("#############################") 

#############################
Best K = 82
Applying K-means
Finished
#############################


In [15]:
m.applyAllMetrics(pca_result,y_pred)

/opt/conda/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


Davies Bouldin
3.2088060820018414

Calinski and Harabaz
36.508938218751474

Silhouette Score
0.050003549537145295



### Keeping variance of 80%

In [16]:
pca = PCA(n_components = 0.85, svd_solver='full')
pca_result = pca.fit_transform(X)

In [17]:
print(pca_result.shape)

(13229, 733)


In [18]:
print("#############################")
print("Best K =", best_K)
print("Applying K-means")
best_cluster = KMeans(n_clusters=best_K, n_jobs=-1)
best_cluster_result = best_cluster.fit(pca_result)
y_pred = best_cluster_result.labels_
print("Finished")
print("#############################") 

#############################
Best K = 82
Applying K-means
Finished
#############################


In [19]:
m.applyAllMetrics(pca_result,y_pred)

Davies Bouldin
3.1434529436217127



/opt/conda/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py:342: RuntimeWarning: divide by zero encountered in true_divide
  score = (intra_dists[:, None] + intra_dists) / centroid_distances


Calinski and Harabaz
35.82918101762059

Silhouette Score
0.05528209657294402

